### ISSUE TITLE
didn't show the differences when the difference is "/n" at the end

### ISSUE THREAD

**Issue by 313183373** [praneshr/react-diff-viewer#9] opened 2019-04-15 02:58 UTC
the oldValue is `"1\n1\n1\n0\n0\n1\n0\n0\n0\n0\n"`
the newValue is `"1\n1\n1\n0\n0\n1\n0\n0\n0\n0"`
the differences is "\n" at the end
react-diff-viewer:
i change the react-diff-viewer props on the demo site
![image](https://user-images.githubusercontent.com/22502857/56105052-1337aa80-5f6d-11e9-9f63-eb7631c41964.png)

**Comment by praneshr** [comment] 2019-05-14 05:31
Duplicate of https://github.com/praneshr/react-diff-viewer/issues/12

**Closed by praneshr** 2019-05-14 05:31 UTC
