### ISSUE TITLE
Having trouble compiling this library in a typescript react project targetting es5

### ISSUE THREAD

**Issue by daniel-trinh** [praneshr/react-diff-viewer#47] opened 2019-11-07 22:49 UTC
I'm not completely sure what's causing this, but I wonder if it's because this project seems to be targetting esnext? The current project I'm on has es5 as the target. The only thing that seems to fix the compilation error below is to set my target to esnext, but that introduces other errors in other files in my project. 

```
./node_modules/react-diff-viewer/lib/styles.js
Module parse failed: Unexpected token (5:42)
You may need an appropriate loader to handle this file type.
| const emotion_1 = require("emotion");
| exports.default = (styleOverride) => {
|     const { variables: overrideVariables, ...styles } = styleOverride;
|     const variables = {
|         ...{
```

**Comment by yykoypj** [comment] 2019-11-12 07:57
I have the same issue, need some help.

**Comment by yykoypj** [comment] 2019-11-12 08:38
I solved this problem by doing as follow：

//webpack  -> modules.rules

test: /\.jsx?$/,
loader: 'babel-loader',
exclude: function (modulePath) {
    return /node_modules/.test(modulePath) &&
        !/node_modules\\react-diff-viewer/.test(modulePath);
}
hope this will help you.

**Comment by andresmgot** [comment] 2019-11-12 12:15
same issue here, I am using `react-scripts-ts` so I cannot change the webpack configuration. Any suggestion?

**Comment by andresmgot** [comment] 2019-11-13 12:36
Any hints here @praneshr? This is preventing me from using the version 2.x of the package

**Comment by praneshr** [comment] 2019-11-13 13:56
@daniel-trinh Can you share your tsconfig.json?

**Comment by andresmgot** [comment] 2019-11-13 15:40
This is my `tsconfig..json`:

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["dom", "es6"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": ["node_modules", "build", "coverage", "scripts", "acceptance-tests", "webpack", "jest"]
}
```

**Comment by daniel-trinh** [comment] 2019-11-13 22:30
here's mine, looks similar to the one above
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ],
  "baseUrl": "./",
  "paths": {
    "react": [
      "node_modules/@types/react"
    ]
  },
  "include": [
    "src"
  ]
}
```

**Comment by praneshr** [comment] 2019-11-14 12:52
Guys, I'm not able to reproduce this issue. I created a new project and used a modified version of your tsconfigs. Everything works fine. 

[Download this zip and check](https://github.com/praneshr/react-diff-viewer/files/3846522/react-diff-experiment.zip)

Run the following commands.
```
yarn install
yarn build
```

I made the target as `esnext` because I wanted the lib files to include all latest syntax. Then, the consumer can change their target according to their needs. 

I'm consuming the lib files for the [examples](https://github.com/praneshr/react-diff-viewer/blob/master/tsconfig.examples.json). It works fine.

**Comment by andresmgot** [comment] 2019-11-14 14:29
I see, I tried with that tsconfig and it's not working for me either so I assume that the problem is other. I am using older versions for typescript and react so that's maybe the issue? I have updated typescript and the problem persists (unfortunately I cannot update react easily). Maybe @daniel-trinh can confirm if that's an issue for him?

**Comment by praneshr** [comment] 2019-11-14 14:51
@andresmgot The zip didn't work for you? Can you confirm the typescript version you're using?

**Comment by andresmgot** [comment] 2019-11-14 15:54
> @andresmgot The zip didn't work for you? Can you confirm the typescript version you're using?

Yes, sorry. The zip works for me, what doesn't work for me is to use that tsconfig in my project (I get the same result, the only change is the `strictNullChecks` so that's why I assumed that the problem is somewhere else.

Regarding my last comment, I have tried again using the latest react ^16.11.0 and typescript ^3.7.2 but the problem is the same so no clue what could be happening...

**Comment by praneshr** [comment] 2019-11-15 05:21
@andresmgot `react-scripts-ts` was updated a year ago. May be the dependencies are old. I will recommend you to use latest webpack or tsc. 

I will keep this bug open for few more days. Let me know if you need my help.

**Comment by praneshr** [comment] 2019-11-22 07:18
Closing this issue as the issue cannot be reproduced in an ideal scenario.

**Closed by praneshr** 2019-11-22 07:18 UTC
Labels: question

**Comment by rokoroku** [comment] 2019-12-09 12:57
>I made the target as esnext because I wanted the lib files to include all latest syntax. Then, the consumer can change their target according to their needs.

@praneshr I think It's better to indicate this module is targeted to ESNEXT in README file, so that we can add this module to the transpiling target.
