### ISSUE TITLE
Evenly split page?

### ISSUE THREAD

**Issue by jordanmmck** [praneshr/react-diff-viewer#46] opened 2019-11-06 00:17 UTC
Apologies if this is documented somewhere, but I couldn't find it. I'm wondering if it is currently possible to give the document on the left and the document on the right even width on the page? Right now one doc often takes up 70-80% of the page width.

**Comment by praneshr** [comment] 2019-11-13 14:01
@jordanmmck Sorry for the delayed response. By default, the component doesn't come with any style rules for the column width. But, this looks like a valid use case. I'll add support for this in the next version.

**Comment by praneshr** [comment] 2019-11-13 14:03
Duplicate of https://github.com/praneshr/react-diff-viewer/issues/48

**Closed by praneshr** 2019-11-13 14:03 UTC
