### ISSUE TITLE
Diff View not displaying subsequent lines when a change is made to the first line.

### ISSUE THREAD

**Issue by najeeta** [praneshr/react-diff-viewer#41] opened 2019-10-29 18:14 UTC
Hi praneshr, 
Thank you for developing this tool! This will be extremely useful for what I am trying to use it for. That being said, I have come across a bug which I hope can be resolved with ease. 

What I am trying to accomplish:
- I have a textarea that will be pre-populated with some text.
- A user will make changes in this textarea and then review their changes using 'react-diff-viewer'

The bug I have come across:
* When line 1 has been modified, the diff viewer will NOT display the proceeding lines of the textarea. 
* When line 1 is not modified, the diff viewer WILL display the proceeding lines of the textarea.

I have attached screenshots illustrating what it happening. 

Step 1 (Initial Content):
<img width="1433" alt="Screen Shot 2019-10-29 at 10 42 56 AM" src="https://user-images.githubusercontent.com/48929241/67795508-974e0d00-fa3b-11e9-9d0a-635dd09e824a.png">

Step 2 (Add Content): 
<img width="1436" alt="Screen Shot 2019-10-29 at 10 43 07 AM" src="https://user-images.githubusercontent.com/48929241/67795599-ba78bc80-fa3b-11e9-8e63-b15a6d75a571.png">

Step 3 (Review Diff):
<img width="1503" alt="Screen Shot 2019-10-29 at 10 43 23 AM" src="https://user-images.githubusercontent.com/48929241/67795626-c5335180-fa3b-11e9-889d-91d1f0e30122.png">

Step 4 (Do not add content to line 1, but add to other lines):
<img width="1438" alt="Screen Shot 2019-10-29 at 10 43 39 AM" src="https://user-images.githubusercontent.com/48929241/67795757-fdd32b00-fa3b-11e9-993a-01360a57eea1.png">

Step 5 (Review content with no changes to line 1. RESULT: Diff displays proceeding lines):
<img width="1503" alt="Screen Shot 2019-10-29 at 10 43 52 AM" src="https://user-images.githubusercontent.com/48929241/67796579-843c3c80-fa3d-11e9-85f3-94dc14bb4dba.png">

**Comment by praneshr** [comment] 2019-10-31 01:31
Hi @najeeta, This is a duplicate of https://github.com/praneshr/react-diff-viewer/issues/32. 

I've published a updated patch now. Please reinstall/upgrade the module.

**Closed by praneshr** 2019-10-31 01:31 UTC
